// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhpGJs28opOu_rlvjHZ1RudPvTDR-k_Js',
    appId: '1:790479544694:android:becee724ce2a9b8a305a57',
    messagingSenderId: '790479544694',
    projectId: 'runkingapp',
    storageBucket: 'runkingapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJX_FbFnO1VBjVry2wV96buJ8ewLA0vs',
    appId: '1:790479544694:ios:d3e75fb69082514f305a57',
    messagingSenderId: '790479544694',
    projectId: 'runkingapp',
    storageBucket: 'runkingapp.appspot.com',
    iosClientId: '790479544694-9pjkd84fkotctcjealm1o3jlufv70fv2.apps.googleusercontent.com',
    iosBundleId: 'br.com.runkingios',
  );
}
