// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEg0FpJsjfI-RxMkt6esfz5hl8VxkafcA',
    appId: '1:577163815637:android:1df9f64b037762b745105c',
    messagingSenderId: '577163815637',
    projectId: 'chattesteflutter-e61c3',
    storageBucket: 'chattesteflutter-e61c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQx7uq1NCxUbrjxB_KpkrCX2S3jWnb3k',
    appId: '1:577163815637:ios:74b0fcc88d320fd445105c',
    messagingSenderId: '577163815637',
    projectId: 'chattesteflutter-e61c3',
    storageBucket: 'chattesteflutter-e61c3.appspot.com',
    iosClientId: '577163815637-5s035k76h5ivi58gn1t904npa53upv8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.astrosApp',
  );
}
